# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bjarne < Formula
  desc "AI-assisted C/C++ code generation with rigorous validation"
  homepage "https://github.com/3rg0n/bjarne"
  version "0.1.3"
  license "MIT"

  depends_on "podman" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.3/bjarne_0.1.3_darwin_amd64.tar.gz"
      sha256 "645dedd4c0644328bc899c19ab5d3577c96a7f9346147847250d8929d2c365ef"

      def install
        bin.install "bjarne"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.3/bjarne_0.1.3_darwin_arm64.tar.gz"
      sha256 "8dba341ca961d518f925dcfe0ba408aa0b901f7808dc49309e2f377f235871c0"

      def install
        bin.install "bjarne"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.3/bjarne_0.1.3_linux_amd64.tar.gz"
      sha256 "6fbed9c7f7059238f89e892526c400c0be1b276cffc3f979c2e4e25c3ad4b176"
      def install
        bin.install "bjarne"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.3/bjarne_0.1.3_linux_arm64.tar.gz"
      sha256 "15f3b966aef419dda49f0c9182e53d33438665bf7b3258dba75d79c623fcff46"
      def install
        bin.install "bjarne"
      end
    end
  end

  def caveats
    <<~EOS
      bjarne requires podman or docker for code validation.
      Install with: brew install podman
    EOS
  end

  test do
    system "#{bin}/bjarne", "--version"
  end
end
