# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bjarne < Formula
  desc "AI-assisted C/C++ code generation with rigorous validation"
  homepage "https://github.com/3rg0n/bjarne"
  version "0.1.5"
  license "MIT"

  depends_on "podman" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.5/bjarne_0.1.5_darwin_amd64.tar.gz"
      sha256 "67b353aeb076ed34a787d430f986ea11c19b0d3d1d527a05fa8709f407b2767c"

      def install
        bin.install "bjarne"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.5/bjarne_0.1.5_darwin_arm64.tar.gz"
      sha256 "b8c4b305138522162481b46d24713cda46cb5c6be4b986a886447355a6e7a9a8"

      def install
        bin.install "bjarne"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.5/bjarne_0.1.5_linux_amd64.tar.gz"
      sha256 "fdd033e3587569da65707b873a79417372d767f4144167b697ceb3cd9c925271"
      def install
        bin.install "bjarne"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/3rg0n/bjarne/releases/download/v0.1.5/bjarne_0.1.5_linux_arm64.tar.gz"
      sha256 "912f5aa06ad9a92182bb21aaa3e25fbd776158131d37c49cca91e273907cbb6d"
      def install
        bin.install "bjarne"
      end
    end
  end

  def caveats
    <<~EOS
      bjarne requires podman or docker for code validation.
      Install with: brew install podman
    EOS
  end

  test do
    system "#{bin}/bjarne", "--version"
  end
end
